name: Python CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up environment variables
      run: |
        echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        echo "MONGO_DB_URI=${{ secrets.MONGO_DB_URI }}" >> $GITHUB_ENV
        echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> $GITHUB_ENV
        echo "PINE_CONE_API=${{ secrets.PINE_CONE_API }}" >> $GITHUB_ENV
        echo "INDEX_NAME_A=${{ secrets.INDEX_NAME_A }}" >> $GITHUB_ENV
        echo "INDEX_NAME_C=${{ secrets.INDEX_NAME_C }}" >> $GITHUB_ENV

    - name: Run tests or deploy
      run: |
        # Your test or deployment command here
        # python app.py  # Example of running your script
